third_party/move/tools/move-mutator/Cargo.toml
third_party/move/tools/move-spec-test/Cargo.toml

For now we will use a modified fork here:
https://github.com/Rqnsom/aptos-core
Until this [PR](https://github.com/aptos-labs/aptos-core/pull/14385) gets merged into the official aptos-core repo.

deps: build mutator with external sources

---

Cargo.lock
Cargo.toml
move-mutator/Cargo.toml
move-spec-test/Cargo.toml

Removing the temporary solution with the modified rqnsom/aptos-core fork. Now, the aptos-core contains the necessary change that has recently been merged:
https://github.com/aptos-labs/aptos-core/pull/14385

dep: use proper aptos-core repo

---

.github/workflows/check-and-lint.yml
Cargo.lock
move-mutator/src/configuration.rs
move-mutator/src/main.rs
move-mutator/src/operators/literal.rs
move-mutator/src/operators/mod.rs
move-mutator/src/report.rs
move-spec-test/src/cli.rs
move-spec-test/src/lib.rs
move-spec-test/src/main.rs
move-spec-test/src/prover.rs

The new worfklow runs:
- `cargo check --all-targets`
- `cargo fmt --all -- --check`
- `cargo clippy --all-targets -- -D warnings`
The PR includes two commits:
- fmt check
- resolved clippy warnings

 ci: basic lint and fmt check 

---

Cargo.lock
move-mutator/Cargo.toml
move-mutator/src/compiler.rs
move-mutator/src/lib.rs
move-mutator/tests/basic_tests.rs

Single files can be mutated only if the files require no deps or address name resolving - in those cases we should printout a proper error in the output.
An example:
```sh
$ ./target/release/move-mutator -m move-mutator/tests/move-assets/simple/sources/Sum.move
error: address with no value
┌─ move-mutator/tests/move-assets/simple/sources/Sum.move:1:8
│
1 │ module TestAccount::Sum {
│        ^^^^^^^^^^^ address 'TestAccount' is not assigned a value. Try assigning it a value when calling the compiler
Error: AST generation failed
```

chore(move-mutator): improve single file err handling

---

move-mutator/tests/move-assets/breakcontinue/Move.toml
move-mutator/tests/move-assets/breakcontinue/sources/Break.move
move-mutator/tests/move-assets/breakcontinue/sources/BreakContinue.move
move-mutator/tests/move-assets/breakcontinue/sources/Continue.move
move-mutator/tests/move-assets/relative_dep/p1/Move.toml
move-mutator/tests/move-assets/relative_dep/p1/sources/Mul.move
move-mutator/tests/move-assets/relative_dep/p2/Move.toml
move-mutator/tests/move-assets/relative_dep/p2/sources/MulUse.move
move-mutator/tests/move-assets/simple/Move.toml
move-mutator/tests/move-assets/simple/sources/Negation.move
move-mutator/tests/move-assets/simple/sources/Operators.move
move-mutator/tests/move-assets/simple/sources/StillSimple.move
move-mutator/tests/move-assets/simple/sources/Sum.move

These projects will be used to conduct testing with the `move-mutation-test` prototype tool that is going to be delivered in another PR.
Early info:
- running the tool against some projects takes a lot of time, e.g. 18 minutes for the project `simple`.

test: add move tests for projects in move-assets

---

move-mutator/src/cli.rs
move-mutator/src/configuration.rs
move-mutator/src/main.rs
move-mutator/src/mutate.rs
move-mutator/tests/basic_tests.rs
move-spec-test/src/lib.rs
move-spec-test/src/main.rs

Adds a CLI argument that allows mutating only specified functions only.
This feature will be used a lot within the `move-mutation-test` tool.

feat(mutator): add include-functions filter CLI arg 

---

.github/workflows/check-and-lint.yml
Cargo.lock
Cargo.toml
move-mutation-test/Cargo.toml
move-mutation-test/README.md
move-mutation-test/src/benchmark.rs
move-mutation-test/src/cli.rs
move-mutation-test/src/lib.rs
move-mutation-test/src/main.rs
move-mutation-test/src/mutation_test.rs
move-mutation-test/src/report.rs
move-mutator/Cargo.toml

The first version of the tool is contained here.
The code structure is based on the move-spec-test tool.
Some notes:
- For unit test build, the compilation must succeed, so `--verify-mutants` option for the mutator is always enabled here
- The tool isn't that slow, but that should be improved with some concurrency features in the future
- For quick testing, we need to be able to generate mutants for specific functions. That would improve overall testing speed.
- Readme and docs will be added separately.

feat: add move-mutation-test tool

---

.github/workflows/check-and-lint.yml
move-mutation-test/src/cli.rs
move-mutation-test/src/lib.rs
move-mutation-test/src/mutation_test.rs
move-mutator/tests/move-assets/basic_coin/Move.toml
move-mutator/tests/move-assets/breakcontinue/Move.toml
move-mutator/tests/move-assets/relative_dep/p1/Move.toml
move-mutator/tests/move-assets/relative_dep/p2/Move.toml
move-mutator/tests/move-assets/simple/Move.toml
move-spec-test/src/lib.rs

Optimization takes use of the `skip-fetch-latest-git-deps` compilation flag.
Regardless of this flag, by default - if no deps are found in the
`/Users/$USER/.move` directory (a cache folder for Move packages)
the missing packages will be downloaded there.
But if the cache exists, then the `skip-fetch-latest-git-deps` flag can
be used to skip checking whether those cached Move packages ought to be
updated.
In this PR - for the first compilation step (checking that the original
tests are working fine), we disable that flag and ensure we get the
latest Move packages.
Then, for all subsequent compilations (mutant generation and running
tests on those mutants), the tool enables that flag since it doesn't
make much sense to check the latest deps repeatedly - checking it only
once when the tool …

refactor: optimize compile speed (skip fetch deps)

---

Cargo.lock
README.md
move-mutation-test/src/cli.rs
move-mutator/src/cli.rs
move-spec-test/src/cli.rs

This PR adds addition command line argument to mutate only specified functions:
```rust
/// Work only over specified functions.
#[clap(short = 'f', long, value_parser, default_value = "all")]
pub mutate_functions: FunctionFilter,
```
to both `move-spec-test` and `move-mutation-test` tools.

feat: add function-filter to spec-test and mutation-test

---

Cargo.lock
Cargo.toml
move-mutation-test/Cargo.toml
move-mutation-test/src/lib.rs
move-mutation-test/src/report.rs

Optimization feature adding rayon into the `move-mutation-test` to
ensure that test execution on each mutant is done in parallel.
Execution speed is between x2 and x3 times improved here.

feat(mutation-test): add rayon for concurrency

---

move-mutator/src/operators/binary_swap.rs
move-mutator/src/report.rs
move-mutator/tests/basic_tests.rs
move-mutator/tests/move-assets/check_swap_operator/Move.toml
move-mutator/tests/move-assets/check_swap_operator/sources/StorageAccess.move

These binary operations have the commutative property:
`+`, `*`, `&`, `&&`, `|`, `||`, `==`, `!=`, `^`
And by default, the mutator shouldn't swap expressions around operators
for these operations.
Except in the case where expressions contain a function or a closure
somewhere in the expression AST tree.
In those cases, the `binary operator swap` should be applied since
functions and closures might affect the values in the expressions
depending on the order of the expressions.
Explore tests under `module 0x42::m2` in the `check_swap_operator`
project under `move-assets` for more info.

chore: improve the binary_operator_swap op

---

README.md

Add a bit to the README about getting Boogie and Z3 installed and set up.

chore: add a section about how to get boogie and z3 set up in README.md

---

.github/workflows/check-and-lint.yml
Cargo.lock
Cargo.toml
move-mutator/Cargo.toml
move-mutator/src/operators/binary.rs
move-mutator/src/report.rs
move-mutator/tests/basic_tests.rs
move-mutator/tests/move-assets/simple/sources/BinaryReplacement.move

To avoid false-positive results with move-spec-test and move-mutation-test, the binary replacement operator has been improved with the following rules:
```
x == 0 should never mutate to x <= 0
0 == x should never mutate to 0 => x
The reverse is not checked: x <= 0 or 0 >= 0 since such code indicates logic error.
x != 0 should never mutate to x > 0
0 != x should never mutate to 0 < x
x > 0 should never mutate to x != 0
0 < x should never mutate to 0 != x
```

chore(mutator): improve binary replace operator

---

Cargo.lock
Cargo.toml
move-mutation-test/src/cli.rs
move-mutation-test/src/lib.rs
move-mutation-test/src/mutation_test.rs
move-mutator/Cargo.toml
move-mutator/src/cli.rs
move-mutator/src/compiler.rs
move-mutator/src/configuration.rs
move-mutator/src/coverage.rs
move-mutator/src/lib.rs
move-mutator/src/mutate.rs
move-mutator/tests/basic_tests.rs

Added a `--coverage` option to both `move-mutator` and `move-mutation-test` tools.
This flag can be used to generate more specific mutants that target only the source code that has unit test coverage.
This can be useful when the test suite lacks tests.

feat: apply coverage file for specific mutants

---

Cargo.lock
Cargo.toml
move-mutator/Cargo.toml

A fork has been used for a temporary period until the change got merged
in aptos-core repo.

deps(Cargo.toml): replace fork with aptos-core and cargo lock update

---

Cargo.lock
Cargo.toml
move-mutation-test/src/lib.rs
move-mutation-test/src/main.rs
move-spec-test/src/lib.rs
mutator-common/Cargo.toml
mutator-common/src/display_report.rs
mutator-common/src/lib.rs
mutator-common/src/report.rs

A new coloured output for the report.txt has been implemented here.
An example:
```text
sources/Sum.move
---------+-----------------------------------------
| module TestAccount::Sum {
|     fun sub(x: u64, y: u64): u64 {
0/4 |         x - y
|     }
|
|     fun sum(x: u128, y: u128): u128 {
4/4 |         let sum_r = x + y;
|         spec {
|                 assert sum_r == x+y;
|         };
|
|         sum_r
|     }
```

feat: impl display-report command

---

.github/workflows/check-and-lint.yml
.gitignore
Cargo.lock
move-spec-test/Cargo.toml
move-spec-test/src/lib.rs

Optimization feature adding rayon into the move-spec-test to
ensure that test execution on each mutant is done in parallel.
Execution speed is between x3 and x4 times improved here.

feat(spec-test): add rayon for concurrency

---

.gitignore
Cargo.lock
move-mutator/Cargo.toml
move-mutator/src/lib.rs
move-spec-test/src/cli.rs

The speed boost is evident below (when mutator tool is combined with mutation-test tool:
New solution:
```sh
$ RUST_LOG=info move-mutation-test run --package-dir move-mutator/tests/move-assets/simple -o report.txt --mutate-modules=Operators
INFO  move_mutation_test::benchmark > In total, mutation testing took 30914 msecs
INFO  move_mutation_test::benchmark > Generating mutants took 16603 msecs
INFO  move_mutation_test::benchmark > Mutation testing took 12516 msecs
INFO  move_mutation_test::benchmark > Min mutation testing time for a mutant: 905 msecs
INFO  move_mutation_test::benchmark > Max mutation testing time for a mutant: 12135 msecs
INFO  move_mutation_test::benchmark > Average mutation testing time for each mutant: 6722 msecs
```
vs old solution:
```sh
$ RUST_LOG=info …
```

feat(move-mutator): add rayon for concurrency

---

move-mutator/src/coverage.rs
move-mutator/src/operators/binary.rs
move-mutator/tests/move-assets/breakcontinue/sources/Break.move
move-mutator/tests/move-assets/breakcontinue/sources/BreakContinue.move
move-mutator/tests/move-assets/breakcontinue/sources/Continue.move

- [chore: fix for the for loop handling](https://github.com/eigerco/move-spec-testing/commit/330d921a592e6c6c13e7d004c49bd3af42540955)
- This is a corner case handling for for loops, where increments
like `i + 1` happens at the bytecode level not visible at the
source code level.
- [chore: fix for the coverage option](https://github.com/eigerco/move-spec-testing/commit/f1195d2c7f345dcd5a1e04bcd26ce4410221e802)
- Ensure span count is nono-zero before accessing the array with the index.

fixes from beta testing

---

move-mutator/src/coverage.rs

All spans need to be sorted before we can apply the merging algorithm.

fix(mutator): sorting in coverage feature

---

README.md
move-spec-test/README.md
move-spec-test/src/main.rs

The spec-test tool has been extended with the additional `display-report` command:
```sh
$  move-spec-test --help
Move specification testing tool
Usage: move-spec-test <COMMAND>
Commands:
run             Runs the specification test tool
display-report  Display the report in a more readable format
help            Print this message or the help of the given subcommand(s)
Options:
-h, --help     Print help
-V, --version  Print version
```
```
$ move-spec-test display-report -p report.txt
The legend is shown below in the table format
===================================┬==================================
mutants killed / mutants in total │ Source code file path
===================================┼==================================
<examples below> │ <Line>
│
│ Line without any mutants
6/8 │ …
```

feat: add display-report cmd to spec-test tool

---

move-mutation-test/src/cli.rs
move-mutation-test/src/lib.rs
move-mutation-test/src/mutation_test.rs

Added new argument `gas-limit` - the maximum gas limit for each test.
Used mainly for disabling mutants with infinite loops. The default value is large enough for most projects.
By using a reasonably large value, we ensure the original test suite will always pass, while mutants with infinite loops will be killed quite quickly.

feat: use `gas-limit` to kill infinite loop mutants

---

Cargo.lock
move-mutation-test/Cargo.toml
move-mutation-test/src/lib.rs
move-spec-test/Cargo.toml
move-spec-test/src/lib.rs
mutator-common/Cargo.toml
mutator-common/src/lib.rs
mutator-common/src/report.rs
mutator-common/src/tmp_package_dir.rs

Ensure the tools never perform any executions within the original package path. Before the tool is started, the package path is cloned to another temp location. Then, all the work is done with that copy of the original project directory.

refactor: optimize dir copy processes

---

move-mutator/src/coverage.rs

Sometimes, a coverage report generated by the `aptos move test --coverage` command will generate a file that contains out of bound indices. We should ignore such spans.
This should be report in the `aptos-core` repo.

chore: incorrect coverage report workaround

---

move-mutation-test/src/lib.rs
move-spec-test/src/lib.rs

Ensure that we store the original input package in the report.txt so the display-report can always be created easily.

chore: add original package to report output

---

Cargo.lock
move-mutation-test/src/main.rs
move-mutation-test/tests/integration_tests.rs
move-spec-test/src/main.rs
move-spec-test/tests/integration_tests.rs
mutator-common/Cargo.toml
mutator-common/src/display_report.rs

`display-report` command has been split into two pieces:
- `coverage`
- `mutants`
Here's the new output for the command:
```
Usage: move-mutation-test display-report [OPTIONS] <COMMAND>
Commands:
coverage  Display report in the coverage format
mutants   Display mutants
help      Print this message or the help of the given subcommand(s)
Options:
-p, --path-to-report <PATH_TO_REPORT>  Report location. The default file is "report.txt" under the same directory [default: report.txt]
-m, --modules <MODULES>                Include specified modules in the report [default: all]
-h, --help                             Print help
-V, --version                          Print version
```
```
Usage: move-mutation-test display-report mutants [OPTIONS]
Options:
--functions <FUNCTIONS>            Include …
```

feat: add command to display mutants

---

move-mutation-test/tests/integration_tests.rs
move-mutator/src/compiler.rs
move-mutator/src/operators/binary.rs
move-mutator/tests/move-assets/simple/report.txt.mutation-exp
move-mutator/tests/move-assets/simple_move_2_features/Move.toml
move-mutator/tests/move-assets/simple_move_2_features/report.txt.mutation-exp
move-mutator/tests/move-assets/simple_move_2_features/report.txt.spec-exp
move-mutator/tests/move-assets/simple_move_2_features/sources/Operators.move
move-mutator/tests/move-assets/skip_mutation_examples/sources/BasicOps.move
move-spec-test/tests/integration_tests.rs

Suppoting new mutations for the following operations:
- "+="
- "-="
- "*="
- "/="
- "%="
- "|="
- "&="
- "^="
- "<<="
- ">>="
Included a new `simple-move-2-features` project and enabled integration tests for both `move-mutation-test` and `move-spec-test` tools.

feat: add move-2 support for compound assignments

---

move-mutation-test/src/lib.rs
move-mutator/src/lib.rs
move-spec-test/src/lib.rs

If we have a single mutant, fetching rayon thread won't work, since rayon won't even be used in such a case.
Do not try to fetch the rayon thread when there is a single mutant present.

fix: ensure the tool can handle low number of mutants

---

move-mutation-test/src/lib.rs
move-mutation-test/src/main.rs
move-spec-test/src/lib.rs
move-spec-test/src/main.rs
mutator-common/src/display_report.rs
mutator-common/src/report.rs

Allow users to display the mutation testing summary from the report.

feat: add `display-report summary` command

---

README.md
move-mutation-test/README.md
move-mutation-test/src/cli.rs
move-mutator/README.md
move-mutator/src/cli.rs
move-mutator/src/main.rs
move-spec-test/README.md
move-spec-test/src/cli.rs
move-spec-test/src/main.rs
mutator-common/src/report.rs

Short CLI args are not used in aptos-core, so our tooling should align. Also: use the `package-dir` (which is more common in `aptos-core`) instead of the `package-path` option.

chore: remove short CLI args

---

Cargo.lock
Cargo.toml
move-mutation-test/src/mutation_test.rs
move-mutation-test/tests/integration_tests.rs
move-mutator/Cargo.toml
move-mutator/src/coverage.rs
move-mutator/src/lib.rs
move-mutator/src/operator.rs
move-mutator/src/output.rs
move-mutator/src/report.rs
move-mutator/tests/move-assets/simple/report.txt.mutation-exp

~If the tool is configured to compute the coverage report before running the mutator and then running the tests (last phase), such a coverage build will set the `MOVE_VM_TRACE` env variable that will basically remain configured forever.~
~In some cases, this will cause tests to fails as env variable will trigger extra IO operations related to the trace file. To avoid this behaviour, we should remove this variable after the generated coverage report.~
AN UPDATE (the above doesn't not work in the end):
There are two fixes here:
- fix for parallel mutant generation (using indexed file can cause file name collisions, so we are using a hash of the mutant in the mutant file name instead)
- disabling process's ability to generate coverage report as by doing that we configure TRACING_ENABLED flag …

fix: parallel mutant generation and disable automatic coverage report generation
